# POST message
POST http://localhost:8081/message
Content-Type: application/json

"Hello World Hello Kido Hello MyFriends MyFriends"


### GET key and counts
GET http://localhost:8081/count-word/hello/60

### GET counts
GET http://localhost:8081/count-all

### GET counts
GET http://localhost:8081/count-range/60